#!/bin/sh
g++ -o Anyaroth \
    Anyaroth/Anyaroth/AidKit.cpp \
    Anyaroth/Anyaroth/AmmoPackage.cpp \
    Anyaroth/Anyaroth/AmmoViewer.cpp \
    Anyaroth/Anyaroth/AnimatedImageUI.cpp \
    Anyaroth/Anyaroth/BadCredits.cpp \
    Anyaroth/Anyaroth/BlackScreenEvent.cpp \
    Anyaroth/Anyaroth/Boss2.cpp \
    Anyaroth/Anyaroth/Boss3.cpp \
    Anyaroth/Anyaroth/Boss3Panel.cpp \
    Anyaroth/Anyaroth/BossSensor.cpp \
    Anyaroth/Anyaroth/BossSword.cpp \
    Anyaroth/Anyaroth/ButtonUI.cpp \
    Anyaroth/Anyaroth/ChangeLevelEvent.cpp \
    Anyaroth/Anyaroth/CreditsPanel.cpp \
    Anyaroth/Anyaroth/CreditsState.cpp \
    Anyaroth/Anyaroth/CreditsStateHUD.cpp \
    Anyaroth/Anyaroth/CutScene.cpp \
    Anyaroth/Anyaroth/DepotPanel.cpp \
    Anyaroth/Anyaroth/BomberGun.cpp \
    Anyaroth/Anyaroth/BossOrbCannon.cpp \
    Anyaroth/Anyaroth/BulletEffect.cpp \
    Anyaroth/Anyaroth/DialogueEvent.cpp \
    Anyaroth/Anyaroth/DialogueTrigger.cpp \
    Anyaroth/Anyaroth/EffectInterface.cpp \
    Anyaroth/Anyaroth/Boss.cpp \
    Anyaroth/Anyaroth/Capsule.cpp \
    Anyaroth/Anyaroth/EnemyLifePanel.cpp \
    Anyaroth/Anyaroth/Event.cpp \
    Anyaroth/Anyaroth/FadeInOutEvent.cpp \
    Anyaroth/Anyaroth/FitCameraEvent.cpp \
    Anyaroth/Anyaroth/FlipEvent.cpp \
    Anyaroth/Anyaroth/FloatingHead.cpp \
    Anyaroth/Anyaroth/FramedImageUI.cpp \
    Anyaroth/Anyaroth/AnimatedSpriteComponent.cpp \
    Anyaroth/Anyaroth/Arm.cpp \
    Anyaroth/Anyaroth/GoodCredits.cpp \
    Anyaroth/Anyaroth/Knife.cpp \
    Anyaroth/Anyaroth/PlayMusicEvent.cpp \
    Anyaroth/Anyaroth/PlaySoundEvent.cpp \
    Anyaroth/Anyaroth/PoleAxe.cpp \
    Anyaroth/Anyaroth/PopUpEvent.cpp \
    Anyaroth/Anyaroth/Laser.cpp \
    Anyaroth/Anyaroth/LaserContainer.cpp \
    Anyaroth/Anyaroth/LaserHandler.cpp \
    Anyaroth/Anyaroth/OrbShotgun.cpp \
    Anyaroth/Anyaroth/SpawnerBoss.cpp \
    Anyaroth/Anyaroth/Sword.cpp \
    Anyaroth/Anyaroth/BackGround.cpp \
    Anyaroth/Anyaroth/BasicPistol.cpp \
    Anyaroth/Anyaroth/BasicRifle.cpp \
    Anyaroth/Anyaroth/BasicShotgun.cpp \
    Anyaroth/Anyaroth/BodyComponent.cpp \
    Anyaroth/Anyaroth/BounceOrbCannon.cpp \
    Anyaroth/Anyaroth/BouncingBulletEffect.cpp \
    Anyaroth/Anyaroth/BomberEnemy.cpp \
    Anyaroth/Anyaroth/Boss1.cpp \
    Anyaroth/Anyaroth/MissileTurret.cpp \
    Anyaroth/Anyaroth/BulletPool.cpp \
    Anyaroth/Anyaroth/Cursor.cpp \
    Anyaroth/Anyaroth/CustomAnimatedSpriteComponent.cpp \
    Anyaroth/Anyaroth/DialoguePanel.cpp \
    Anyaroth/Anyaroth/DialogueTextUI.cpp \
    Anyaroth/Anyaroth/DistanceEnemy.cpp \
    Anyaroth/Anyaroth/EnemyArm.cpp \
    Anyaroth/Anyaroth/GameManager.cpp \
    Anyaroth/Anyaroth/GravityBombCannon.cpp \
    Anyaroth/Anyaroth/GravityBombDebuff.cpp \
    Anyaroth/Anyaroth/GravityBulletEffect.cpp \
    Anyaroth/Anyaroth/Interactable.cpp \
    Anyaroth/Anyaroth/MainMenuPanel.cpp \
    Anyaroth/Anyaroth/MenuStateHUD.cpp \
    Anyaroth/Anyaroth/MoveEvent.cpp \
    Anyaroth/Anyaroth/NPC.cpp \
    Anyaroth/Anyaroth/ImprovedRifle.cpp \
    Anyaroth/Anyaroth/ImprovedShotgun.cpp \
    Anyaroth/Anyaroth/GroundEnemy.cpp \
    Anyaroth/Anyaroth/LevelManager.cpp \
    Anyaroth/Anyaroth/Map.cpp \
    Anyaroth/Anyaroth/ExplosiveBulletEffect.cpp \
    Anyaroth/Anyaroth/FlyingEnemy.cpp \
    Anyaroth/Anyaroth/Missile.cpp \
    Anyaroth/Anyaroth/MovingComponent.cpp \
    Anyaroth/Anyaroth/Melee.cpp \
    Anyaroth/Anyaroth/Particle.cpp \
    Anyaroth/Anyaroth/ParticleManager.cpp \
    Anyaroth/Anyaroth/ParticlePool.cpp \
    Anyaroth/Anyaroth/OptionsPanel.cpp \
    Anyaroth/Anyaroth/PausePanel.cpp \
    Anyaroth/Anyaroth/PauseStateHUD.cpp \
    Anyaroth/Anyaroth/PiercingBulletEffect.cpp \
    Anyaroth/Anyaroth/PlasmaSniper.cpp \
    Anyaroth/Anyaroth/PlayerArm.cpp \
    Anyaroth/Anyaroth/BossPanel.cpp \
    Anyaroth/Anyaroth/Bullet.cpp \
    Anyaroth/Anyaroth/Camera.cpp \
    Anyaroth/Anyaroth/Canvas.cpp \
    Anyaroth/Anyaroth/Coin.cpp \
    Anyaroth/Anyaroth/CoinsCounter.cpp \
    Anyaroth/Anyaroth/Collectable.cpp \
    Anyaroth/Anyaroth/CollisionManager.cpp \
    Anyaroth/Anyaroth/DashViewer.cpp \
    Anyaroth/Anyaroth/DebugDraw.cpp \
    Anyaroth/Anyaroth/DistanceDynamicEnemy.cpp \
    Anyaroth/Anyaroth/DistanceStaticEnemy.cpp \
    Anyaroth/Anyaroth/Enemy.cpp \
    Anyaroth/Anyaroth/FollowingComponent.cpp \
    Anyaroth/Anyaroth/ObjectLayer.cpp \
    Anyaroth/Anyaroth/ImageUI.cpp \
    Anyaroth/Anyaroth/LifeBar.cpp \
    Anyaroth/Anyaroth/Life.cpp \
    Anyaroth/Anyaroth/MartyrEnemy.cpp \
    Anyaroth/Anyaroth/MeleeEnemy.cpp \
    Anyaroth/Anyaroth/PanelUI.cpp \
    Anyaroth/Anyaroth/ParallaxBackGround.cpp \
    Anyaroth/Anyaroth/ParallaxLayer.cpp \
    Anyaroth/Anyaroth/Player.cpp \
    Anyaroth/Anyaroth/FrameComponent.cpp \
    Anyaroth/Anyaroth/Game.cpp \
    Anyaroth/Anyaroth/GameObject.cpp \
    Anyaroth/Anyaroth/GameState.cpp \
    Anyaroth/Anyaroth/GameStateMachine.cpp \
    Anyaroth/Anyaroth/Gun.cpp \
    Anyaroth/Anyaroth/InputComponent.cpp \
    Anyaroth/Anyaroth/main.cpp \
    Anyaroth/Anyaroth/MenuState.cpp \
    Anyaroth/Anyaroth/PauseState.cpp \
    Anyaroth/Anyaroth/PhysicsComponent.cpp \
    Anyaroth/Anyaroth/PlayerPanel.cpp \
    Anyaroth/Anyaroth/PlayState.cpp \
    Anyaroth/Anyaroth/PlayStateHUD.cpp \
    Anyaroth/Anyaroth/BossPoleAxe.cpp \
    Anyaroth/Anyaroth/PoolWrapper.cpp \
    Anyaroth/Anyaroth/PopUpPanel.cpp \
    Anyaroth/Anyaroth/RenderComponent.cpp \
    Anyaroth/Anyaroth/ShakeEvent.cpp \
    Anyaroth/Anyaroth/Shop.cpp \
    Anyaroth/Anyaroth/ShopEvent.cpp \
    Anyaroth/Anyaroth/ShopInfoPanel.cpp \
    Anyaroth/Anyaroth/ShopMenu.cpp \
    Anyaroth/Anyaroth/ShopItem.cpp \
    Anyaroth/Anyaroth/CatalogPanel.cpp \
    Anyaroth/Anyaroth/Shotgun.cpp \
    Anyaroth/Anyaroth/SoundManager.cpp \
    Anyaroth/Anyaroth/SpawnerEnemy.cpp \
    Anyaroth/Anyaroth/SpriteComponent.cpp \
    Anyaroth/Anyaroth/Money.cpp \
    Anyaroth/Anyaroth/SpriteObject.cpp \
    Anyaroth/Anyaroth/StaticFlyingEnemy.cpp \
    Anyaroth/Anyaroth/StaticSpawnerEnemy.cpp \
    Anyaroth/Anyaroth/TextUI.cpp \
    Anyaroth/Anyaroth/Texture.cpp \
    Anyaroth/Anyaroth/Tilemap.cpp \
    Anyaroth/Anyaroth/TransformComponent.cpp \
    Anyaroth/Anyaroth/Trigger.cpp \
    Anyaroth/Anyaroth/TTFclass.cpp \
    Anyaroth/Anyaroth/TutorialBuddy.cpp \
    Anyaroth/Anyaroth/TutorialBullsEye.cpp \
    Anyaroth/Anyaroth/TutorialTurret.cpp \
    Anyaroth/Anyaroth/UIElement.cpp \
    Anyaroth/Anyaroth/Vector2D.cpp \
    Anyaroth/Anyaroth/WaitingEvent.cpp \
    Anyaroth/Anyaroth/WeaponManager.cpp \
    Anyaroth/Anyaroth/WeaponryViewer.cpp \
    Anyaroth/Anyaroth/ZoomInOutEvent.cpp \
-lSDL -std=c++11 -Wno-unused-local-typedefs
